language: node_js
node_js:
  - "10"
install:
  - npm install --no-save --no-save lerna@3.4.2 qunit@2.7.1 @babel/register@7.0.0 @babel/core@7.1.2 @babel/plugin-transform-modules-commonjs@^7.1.0 ts-node@7.0.1 typescript@3.1.6 tslint@5.11.0 eslint@5.0.0
script:
  - ./node_modules/.bin/lerna run test
  - ./node_modules/.bin/lerna run lint
