language: node_js
node_js:
  - "10"
cache:
  directories:
    - node_modules
install:
  - npm install --no-save lerna@3.20.2 microbundle@0.12.0-next.7 qunit@2.9.3 ts-node@8.6.2 typescript@3.7.5 tslint@6.0.0 eslint@5.0.0 @types/qunit@2.9.0
script:
  - ./node_modules/.bin/lerna run test
  - ./node_modules/.bin/lerna run lint
