sudo: required
dist: trusty

language: node_js
node_js:
  - "9"

addons:
  chrome: stable
  firefox: latest

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - make bootstrap

script:
  - make lint
  - make test
