language: node_js
node_js:
  - "10"
cache:
  yarn: true
  directories:
    - node_modules
install:
  - npm install -g qunit@2.6.1
  - npm install --no-save babel-register@6.26.0 babel-plugin-transform-es2015-modules-commonjs@6.26.2
script:
  - qunit --require babel-register packages/**/tests/
