dist: trusty

language: node_js

addons:
  chrome: stable
  firefox: stable

# before_install:
#   - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - make bootstrap

script:
  - make test